### ISSUE TITLE
Support for MySQL

### ISSUE THREAD

**Issue by micheldewit** [FabioZumbi12/Sponge-RankUpper#12]
Hi there! I am writing, in hope, that you could write support for MySQL!
The following is the issue: We have RankUpper on our network, and we are loving it, however, because each server counts it individually, this means Each server has their own counting time etc. 
We want to "globalize" it, and would love if it could be connected to our SQL server.

**Comment by FabioZumbi12** [comment]
RankUpper need to work fine with most permissions plugins before i work is other features. But with time, i ll add ;)
