### ISSUE TITLE
Double Rankup

### ISSUE THREAD

**Issue by GershonR** [FabioZumbi12/Sponge-RankUpper#13]
I had a user get ranked up automatically fine, but then another user joined it ranked him up, but also the previous user who got ranked up another time.

Using LuckPerms and RankUpper 3.0.0 from your Ore Page

**Comment by GershonR** [comment]
Update: This causes you to rankup right away when you get an automatic rankup and then you run /ru check which causes you to rank up again

**Comment by Bolly12321** [comment]
This project is no longer maintained unfortunately

**Comment by FabioZumbi12** [comment]
I get back to work on this. Download the latest version from Ore (3.0.1).
