### ISSUE TITLE
Rank Upper is not working correctly

### ISSUE THREAD

**Issue by SeanOMik** [FabioZumbi12/Sponge-RankUpper#16]
I have 2 ranks in rank upper on a 1.10.2 spongeforge server. After the player ranks up to the 2nd rank and types /ru check it ranks them back up to the 2nd one but not the 3rd one.

`default {
    # Commands to execute when promote. These commands will depend on your permission plugin.
    execute-commands=[
        "lp user {player} parent remove {oldgroup}",
        "lp user {player} parent set regular"
    ]
    message-broadcast="&a>> The player &6{player} &ahas played for &6{time} &aand now is rank {newgroup} on server."
    minutes-needed=300
    next-group=regular
}
regular {
    execute-commands=[
        "lp user {player} parent remove group {oldgroup}",
        "lp user {player} parent add group babygor"
    ]
    message-broadcast="&a>> The player &6{player} &ahas played for &6{time} &aand now is rank {newgroup} on server."
    minutes-needed=720
    next-group=babygor
}`

I am using lucky perms not pex. The rank up thing for lucky perms works but it never ranks the player to the babygor group.

**Comment by FabioZumbi12** [comment]
Try the latest version and use LuckPerms to avoid some problems.
