### ISSUE TITLE
Rank Up requirement based on Statistics

### ISSUE THREAD

**Issue by EverNife** [FabioZumbi12/Sponge-RankUpper#18]
Something like this

"The player needs:

![image](https://user-images.githubusercontent.com/11357801/30729160-e5b671ae-9f33-11e7-9ab3-3fc6fd186a0a.png)
"

**Comment by FabioZumbi12** [comment]
Try the latest version from our jenkins http://areaz12server.net.br:8080/job/RankUpper/

Just add the statistic name and the value with other statistics and test. I didnt tested yet.

**Comment by EverNife** [comment]
Sorry, seems to be good!

Ty! :D
