### ISSUE TITLE
Has it updated? What version am I using?

### ISSUE THREAD

**Issue by KiriCattus** [FabioZumbi12/Sponge-RankUpper#2]
Could you try and add versioning to each release to try and help any server staff determine if you have released a new version as it is kinda hard to do a plugin update without knowing if its updated or not and takes extra time when we just have to download and assume its updated. I know this seams like such a small detail but it really helps keep frustration levels down when it gets busy. Doesn't have to be in the actual code just in the name of the jar that's all it would make so many server staff happy xD

**Comment by KiriCattus** [comment]
Something I forgot to mention is the plugin ID you used is not the way its meant to be done and it throws errors into the servers console but all you need to do is change this 'de.randombyte.holograms' into this 'holograms' in the main class :)

**Comment by ProsperCraft** [comment]
^ Please version your file names.

Here is an example of someone doing a great job at that - https://github.com/NucleusPowered/Nucleus/releases/
https://github.com/Flibio/EconomyLite/releases

**Comment by FabioZumbi12** [comment]
I can, but the problem its actually ha no releases, only dev builds :/

Anyway i already configured to add buil versions on .jar file ;)
