### ISSUE TITLE
Sponge/Permission error

### ISSUE THREAD

**Issue by Yorkforce** [FabioZumbi12/Sponge-RankUpper#20]
Currently having a few issues getting this work, we used to run it fine on 1.10 but on our 1.12 Horizons server its throwing this error whenever we run the /ru check command:
https://pastebin.com/xyeBVDtB

spongeforge-1.12.2-2529-7.0.0-BETA-2732
RankUpper-5.0-6.0-3.0.1-b207
LuckPerms-Sponge-3.4.52

**Comment by FabioZumbi12** [comment]
Its because you is using api 5-6 on 1.12.2 (api 7). On dev buils theres an api 7 version: http://areaz12server.net.br:8080/job/RankUpper/

**Comment by Yorkforce** [comment]
Ahh I see it now, thanks. I just saw the notes on the download page saying (api7) Hadn't realised there were 2 versions.
