### ISSUE TITLE
Player-info displays incorrect information

### ISSUE THREAD

**Issue by AustinOveraitis** [FabioZumbi12/Sponge-RankUpper#26]
This bug occurs with the newest RU version 4.0.0.

When console or a player uses the /ru player-command, it displays incorrect information.
For example, when I check my own information, it says I joined 3/4/18 and last joined at 3/4/18 despite being on today and joining far earlier than that.

As an added smaller bug, it says "Joind Date" while it should say "Joined Date"

**Comment by FabioZumbi12** [comment]
Tryed the latest dev build? https://discord.gg/WKaPPmU
