### ISSUE TITLE
Mysql is not supported!

### ISSUE THREAD

**Issue by bigenergy** [FabioZumbi12/Sponge-RankUpper#30]
https://github.com/FabioZumbi12/Sponge-RankUpper/blob/master/RankUpper-56/src/main/java/br/net/fabiozumbi12/RankUpper/config/PlayerStatsDB.java

"MERGE INTO %splayers(%s, %s, %s, %s, %s) values(?, ?, ?, ?, ?)" MERGE INTO is not supported for MySQL, therefore plugin can not update the playtime in the database

Please fix this problem :(

**Comment by bigenergy** [comment]
For MYSQL use "ON DUPLICATE KEY UPDATE"

**Comment by FabioZumbi12** [comment]
Added on latest build, thanks <3
