### ISSUE TITLE
People randomly ranking up

### ISSUE THREAD

**Issue by infamyreloaded** [FabioZumbi12/Sponge-RankUpper#31]
I'm not sure if this in intentional or not. I use your plugin to rank up people when they get a certain amount of money. The problem is that they are auto ranking up when they have that much money. So if my rank 3 cost $4000 and that user has $5000 it will auto rank them up randomly. It's not that big of deal but I would prefer if they had to rankup by using the /ru check command.

Running version: RankUpper-4.0.2-b14-Universal.jar 

This what the ranks look like.
`    "2" {

        execute-commands=[

            "adminpay {player} -10000",

            "lp user {player} parent add {newgroup}",

            "lp user {player} parent remove {oldgroup}",

            "give {player} minecraft:coal 32"
        ]
        levels-needed=0

        message-broadcast="&6[&c&lTWC&6] &e&l{player} &6ranked up to level &e&l{newgroup}&6!"

        minecraft-statistics {

            "MOB_KILLS"=1

        }

        minutes-needed=0

        money-needed=10000

        next-group=3`

**Comment by FabioZumbi12** [comment]
Added a feature on latest dev build to make thia an option.
