### ISSUE TITLE
Rank up

### ISSUE THREAD

**Issue by Millificent** [FabioZumbi12/Sponge-RankUpper#32]
We have an existing server so would like to incorporate their timings.
We are  trying to "add minutes" but upon relogging everything is reset even after using the save all command.

Any help would be appreciated

https://gist.github.com/Millificent/9dd4dda1e905aab53ba185045bb90fe2

**Comment by FabioZumbi12** [comment]
I see no problems and theres no errors logs. Check the console for errors!
