### ISSUE TITLE
Rank up doesn't continue to the next rank and keeps ranking up the same rank

### ISSUE THREAD

**Issue by Coolkc456** [FabioZumbi12/Sponge-RankUpper#33]
For some reason the ranking up doesn't stop after this one particular rank. I've tried remaking the rank and restarting the server but it simply allows the player to /ru rankup until they run out of requirements. In this case, it was only money.
![image](https://user-images.githubusercontent.com/19354446/54168093-4d300100-4443-11e9-926b-0604522d312b.png)
Here's my config: [https://pastebin.com/tAA10WGJ](url)

Any help would be appreciated c:

**Comment by FabioZumbi12** [comment]
The config url is broken, and whats the name of your rankupper jar?
Try the latest dev build too!

**Comment by Coolkc456** [comment]
Thanks for responding. :) I just tried the dev build version 4.0.3-b17 but I still have the same problem.

And sorry about the URL being broken. Can you try this one? https://pastebin.com/veQhDE7v

**Comment by FabioZumbi12** [comment]
Seems your lp command is wrong. I think should be "parent set" not "group add"

**Comment by Coolkc456** [comment]
But it works for all the groups except Breeder. After Breeder, the command should stop or move on to the next rank but it doesn't even if a rank was there. It just loops with Breeder. If I remove Breeder, the plugin will stop at the previous rank like it's supposed to.

**Comment by Coolkc456** [comment]
I changed all the LP commands to /lp {player} parent set {newgroup} but I get the same problem.
https://pastebin.com/2QMT4Ans

**Comment by FabioZumbi12** [comment]
Using my latest version with no issues! Check your groups inheritances or try to recriate that group! I cant reproduce in any way :/
