### ISSUE TITLE
https://pastebin.com/d6g9Bat6[BUG] 

### ISSUE THREAD

**Issue by XMaxTheKillerX** [FabioZumbi12/Sponge-RankUpper#35]
https://pastebin.com/d6g9Bat6
https://prnt.sc/n0pc5a

Hi Guys,

I am currently using this plugin with great fun! I get a lot of possitive feedback so props to you!
but when I use the command /ru check underneath the playtime I get an error message. Can you maybe check it out.

Thanks in advance

**Comment by FabioZumbi12** [comment]
What version of RU and build (the name of your ru .jar)

**Comment by iMystxc** [comment]
Also posting ur config will make it quicker in finding the problem, if it's a problem within the conf

**Comment by FabioZumbi12** [comment]
Seems you have added an invalid statistic on statisics section. The log says `getStatisticData`.
