### ISSUE TITLE
SQL Syntax Error

### ISSUE THREAD

**Issue by travisrroy** [FabioZumbi12/Sponge-RankUpper#36]
Running beta build 17 and 20, I've been having this issue where the hours aren't being updated and a SQL Syntax error is popping up in the console. 

![RankUpper Error](https://user-images.githubusercontent.com/24424190/56008763-4ba86180-5cab-11e9-8d07-0005738226bf.JPG)

**Comment by FabioZumbi12** [comment]
Have you added mode=mysql on uri? You can delete the uri config to generate the correct one.

**Comment by travisrroy** [comment]
This is currently what I have: 
![image](https://user-images.githubusercontent.com/24424190/56016424-31ca4700-5cca-11e9-85b8-63a82631d4a8.png)

**Comment by FabioZumbi12** [comment]
This is the problem, you need to delete this configuration section and let generate a new one with the correct information.
