### ISSUE TITLE
[Request] Make RankUpper work with other permission plugins aswell

### ISSUE THREAD

**Issue by Whazaaaaa** [FabioZumbi12/Sponge-RankUpper#4]
As of now RankUpper works only with PEX. However since PEX hasnt been updated since the end of July it seems that other Permission Managers will likely take over PEX for Sponge. 

As of right now LuckyPerms and PermissionManager are the 2 up and coming PEXlike permissions plugins. 
If you are able to make RankUpper read in what group a player is form that plugin this would be great!

Thanks for the plugin!

**Comment by FabioZumbi12** [comment]
Try this version: https://forums.spongepowered.org/t/chart-with-upwards-trend-rank-upper-v-2-2/12423/123?u=fabiozumbi12

**Comment by KiriCattus** [comment]
Might want to look into making it work with LuckPerms since that seams to be the more widly used permissions plugin at the moment and the developer Luck has been updating it almost daily when I was in his discord chat

**Comment by FabioZumbi12** [comment]
Try now the latest release: https://github.com/FabioZumbi12/Sponge-RankUpper/releases
