### ISSUE TITLE
Typos in default configs

### ISSUE THREAD

**Issue by Magiklynx** [FabioZumbi12/Sponge-RankUpper#7]
In the default files, there are multiple typos. 

An example is in playerstats.conf, an example is it reads "LastVisist" with an extra s, instead of "LastVisit"

and in langEN-US.ini the  requirements on line 15 (commands.help.setgroup) requirements is spelt requeriments, this is duplicated on line 34 (config.setgroup)

**Comment by FabioZumbi12** [comment]
All fixed xD Thanks.
